- backend/platoon_console_proj/cohort/admin.py
- backend/platoon_console_proj/cohort/apps.py
- backend/platoon_console_proj/cohort/models.py
- backend/platoon_console_proj/cohort/tests.py
- backend/platoon_console_proj/cohort/views.py
- backend/platoon_console_proj/group/admin.py
- backend/platoon_console_proj/group/apps.py
- backend/platoon_console_proj/group/models.py
- backend/platoon_console_proj/group/tests.py
- backend/platoon_console_proj/group/views.py
- backend/platoon_console_proj/personal_data/admin.py
- backend/platoon_console_proj/personal_data/apps.py
- backend/platoon_console_proj/personal_data/models.py
- backend/platoon_console_proj/personal_data/tests.py
- backend/platoon_console_proj/personal_data/views.py
- backend/platoon_console_proj/user/admin.py
- backend/platoon_console_proj/user/apps.py
- backend/platoon_console_proj/user/models.py
- backend/platoon_console_proj/user/tests.py
- backend/platoon_console_proj/user/views.py
Added applications for cohort, group, and user.  Started model for user account and cohort. Database has not been created or specified in settings.
> Add applications

- frontend/platoon-console/src/components/Calendar.jsx
- frontend/platoon-console/src/components/Demo.jsx
- frontend/platoon-console/src/components/NavBar.jsx
- frontend/platoon-console/src/components/Pairs.jsx
- frontend/platoon-console/src/components/RollCall.jsx
- frontend/platoon-console/src/main.jsx
- frontend/platoon-console/src/pages/Errorpage.jsx
- frontend/platoon-console/src/pages/Homepage.jsx
- frontend/platoon-console/src/pages/Login.jsx
- frontend/platoon-console/src/pages/Logout.jsx
- frontend/platoon-console/src/pages/Password.jsx
- frontend/platoon-console/src/router.jsx
built structure for frontend
- Closes #15 
Gives more structure and organization
> build out initial structure of pages and components

- frontend/platoon-console/src/custom.scss
- frontend/platoon-console/src/pages/Login.jsx
Updates Login.jsx to have a link to Register.jsx (doesn't exist yet) below the login form.
- Closes #1
> 1-build-login-page

- frontend/platoon-console/src/pages/Errorpage.jsx
Updated "Error 404" text to use established class "mainH2" to match other pages, plush a marginTop of 30px.
- Closes #46
> 43-update-error-head-style

- frontend/platoon-console/src/pages/Errorpage.jsx
Update the Error page layout, included NavBar, refactored code, added button as well for homepage redirect.
- Closes #56
> Refactor & Update Error page with navbar, homepage redirection, and window scaling

- frontend/platoon-console/src/pages/Register.jsx
Make axios request https
- Closes #62 
(In this section, describe how to QA/review your PR. Feel free to use screenshots and/or short videos)
> make axios call https

- frontend/platoon-console/src/App.jsx
- frontend/platoon-console/src/components/NavBar.jsx
- frontend/platoon-console/src/custom.scss
- frontend/platoon-console/src/pages/Homepage.jsx
- frontend/platoon-console/src/pages/Login.jsx
- frontend/platoon-console/src/pages/Register.jsx
Updated frontend to handle login routing, some style changes, mostly updated Homepage.jsx with student content
- Closes #70
> 70 update app navbar rendering

- frontend/platoon-console/src/components/Groupings.jsx
- frontend/platoon-console/src/custom.scss
Updated style for Groupings.jsx
- Closes #11
> Updated style for Groupings.jsx

- frontend/platoon-console/src/pages/Homepage.jsx
Updated Homepage dashboard
- Closes #83
> 83 update homepage dashboard

- frontend/platoon-console/src/components/Accountability.jsx
- frontend/platoon-console/src/custom.scss
- frontend/platoon-console/src/pages/Homepage.jsx
- frontend/platoon-console/src/pages/Login.jsx
Created and implemented Accountability component.  Updated custom.scss.
- Closes #96
> 96 build attendance component

- backend/API-DOCUMENTATION.md
- backend/platoon_console_proj/accountability_app/models.py
- backend/platoon_console_proj/accountability_app/serializers.py
- backend/platoon_console_proj/accountability_app/urls.py
- backend/platoon_console_proj/accountability_app/views.py
- frontend/platoon-console/src/components/Accountability.jsx
- Updates API Documentation to include Endpoints for Instructor Interaction w/ Attendance
- Fixed Logic in APIView
- AttendanceRecordsSerializer (Fixed)
- AdminAttendanceOverride (New)
- alter/<int:record_id>/ ( New URL)
- Closes # (add the ticket number here, like #1)
(In this section, describe how to QA/review your PR. Feel free to use screenshots and/or short videos)
> 90 bug role call backend updating student attendance key values individually

- backend/API-DOCUMENTATION.md
- backend/platoon_console_proj/demo/serializers.py
- backend/platoon_console_proj/demo/views.py
- backend/platoon_console_proj/user_app/views.py
- frontend/platoon-console/src/App.jsx
- frontend/platoon-console/src/components/Demo.jsx
- frontend/platoon-console/src/pages/Homepage.jsx
-Fixed redirect with addition of regex "?" for optional / ending
-Tested Instructor/Student Permissions
- Closes #103
> 103 user permissions backend applying instructor + student logic to api views

- frontend/platoon-console/src/pages/VideoGallery.jsx
This PR adds ability to sort videos by Date or Title
- Closes #65
> 65 Added functionality for ordering videos by Date or Title

- frontend/platoon-console/src/pages/Homepage.jsx
Added navigation capability to Videos/ page
- Closes #65 
Verify appearance and navigation react correctly
> Added Card with navigation to Videos Page for testing

- frontend/platoon-console/src/components/Demo.jsx
- frontend/platoon-console/src/custom.scss
* Updates student card layout / style to match RollCall.
* Auto sorts by status ('on deck', 'to do', 'complete').
* Adds Cohort dropdown selection.
* Adds Random On Deck button.
* If student manually set to 'on deck' replaces existing 'on deck'.
* Modifies Reset button to match style.
- Closes #125
> Refactored Demo to match RollCall

- backend/API-DOCUMENTATION.md
- backend/platoon_console_proj/demo/admin.py
- backend/platoon_console_proj/demo/models.py
- backend/platoon_console_proj/demo/serializers.py
- backend/platoon_console_proj/demo/urls.py
- backend/platoon_console_proj/demo/views.py
- backend/platoon_console_proj/teams/models.py
This adds team demo functionality endpoints
Added ManyToOne Relationship between Team and Cohort - New Migrations will need to be performed
- Closes #127
> 127 demo backend extend to team demos

- backend/API-DOCUMENTATION.md
- backend/platoon_console_proj/demo/admin.py
- backend/platoon_console_proj/demo/models.py
- backend/platoon_console_proj/demo/serializers.py
- backend/platoon_console_proj/demo/urls.py
- backend/platoon_console_proj/demo/views.py
- backend/platoon_console_proj/platoon_console_proj/settings.py
- backend/platoon_console_proj/teams/models.py
- backend/platoon_console_proj/teams/serializers.py
- backend/platoon_console_proj/teams/urls.py
- backend/platoon_console_proj/teams/views.py
Created a view for adding teams.  Created a view for updating, deleting, and adding team members.  Edited API documentation to capture this.
> 132 132 backend add cohort field on teams model

- backend/API-DOCUMENTATION.md
- backend/platoon_console_proj/user_app/admin.py
- backend/platoon_console_proj/user_app/models.py
- backend/platoon_console_proj/user_app/permissions.py
- backend/platoon_console_proj/user_app/serializers.py
- backend/platoon_console_proj/user_app/urls.py
- backend/platoon_console_proj/user_app/views.py
-Added Enpoints with APIVIEWs,urls,serializers for access and manipulating User Details that now includes Slack Handle and Github Handle.
-Added Endpoint for instructors only to get all user details in one endpoint for a master list.
-Updated IsStudent Permissions do to it not allowing PUT, PATCH requests.
- Updated API Documents for these added features.
> 114 user settings backend expanding models to include more details for access ie GitHub handle slack handle

- backend/platoon_console_proj/accountability_app/views.py
- backend/platoon_console_proj/demo/views.py
- backend/platoon_console_proj/gh_api/views.py
- backend/platoon_console_proj/personal_data/admin.py
- backend/platoon_console_proj/personal_data/apps.py
- backend/platoon_console_proj/personal_data/models.py
- backend/platoon_console_proj/personal_data/tests.py
- backend/platoon_console_proj/personal_data/views.py
- backend/platoon_console_proj/teams/views.py
- backend/platoon_console_proj/user_app/views.py
-Error Logic for application_app,user_app,gh_app, teams_app, demo_app
- Standardized responses i.e. {"message": "Custom msg on good response"} // {"error": "Error response from endpoint"} // {response.data} <-- On good data retrieval
> 140 errorhandling backendfrontend fixing error messaging in drf and response handling on frontend

- backend/platoon_console_proj/user_app/views.py
Added Logic to Login Method to decipher between Student / Instructor
- Closes #143
> Fixed Login Logic to Handle between student and instructor

- backend/platoon_console_proj/accountability_app/views.py
- frontend/platoon-console/index.html
- frontend/platoon-console/src/components/Groupings.jsx
- Handles Demo Grouping Logic on the Frontend
- Closes #122
> 122 get endpoint for programm pairing

- frontend/platoon-console/src/components/Demo.jsx
This PR adds Team Demo functionality to the frontend
This has conditional rendering for student or team demos based on what is selected
- Closes #142
> 142 demo frontend add team demo functionality to component

- backend/platoon_console_proj/user_app/serializers.py
- backend/platoon_console_proj/user_app/views.py
- frontend/platoon-console/src/components/RollCall.jsx
- frontend/platoon-console/src/pages/ChangePassword.jsx
- frontend/platoon-console/src/pages/ForgotPassword.jsx
- frontend/platoon-console/src/pages/Homepage.jsx
- frontend/platoon-console/src/pages/Login.jsx
- frontend/platoon-console/src/pages/Register.jsx
- frontend/platoon-console/src/pages/VideoGallery.jsx
* Fixes frontend validation error issues on all forms
* Updates Daily Agenda calendar modal size from 'xl' to 'md'
* Updates YouTube page button from type 'bootstrap-react' to 'reactstrap'
* Updates RollCall page timezone from UTC to 'America/Chicago'
* Updates Modal background and header colors
- Closes #139
> 139 calendar modal yt button timezone

- frontend/platoon-console/src/components/Demo.jsx
- frontend/platoon-console/src/components/RollCall.jsx
- frontend/platoon-console/src/custom.scss
- frontend/platoon-console/src/pages/Login.jsx
- frontend/platoon-console/src/pages/Register.jsx
* Cards and buttons on Demo page conditionally render.
* Instructors now see student's status instead of the word "Status" on the dropdown and can change the status.
* Students see an inactive button with the status displayed as button text.
* Random and Reset buttons only appear to Instructors and are assigned classes to display better, esp for mobile.
* Upon successful Registration user is no longer auto-logged in; gets navigated to /login/.
* Upon successful Login user no longer receives a success message, gets navigated to home/dashboard.
- Closes #149
> 149 conditionally render demo cards

- frontend/platoon-console/src/components/Accountability.jsx
- frontend/platoon-console/src/components/Demo.jsx
- frontend/platoon-console/src/components/Groupings.jsx
- frontend/platoon-console/src/components/RollCall.jsx
- frontend/platoon-console/src/components/StudentAttCard.jsx
- frontend/platoon-console/src/pages/ChangePassword.jsx
- frontend/platoon-console/src/pages/ForgotPassword.jsx
- frontend/platoon-console/src/pages/Homepage.jsx
- frontend/platoon-console/src/pages/Login.jsx
- frontend/platoon-console/src/pages/Register.jsx
- frontend/platoon-console/src/pages/VideoGallery.jsx
This PR changes the Django endpoints from https to http
This solves the SSL issues that have been intermittent during development
Running the server will now return to `python manage.py runserver`
- Closes #152 
> 152 remove ssl frontend change backend links from https to http

- frontend/platoon-console/src/components/Groupings.jsx
Reverted to MVP grouping. Added leftover functionality. Added No attendance Alert
- Closes # (add the ticket number here, like #1)
(In this section, describe how to QA/review your PR. Feel free to use screenshots and/or short videos)
> Reverted to MVP grouping. Added leftover functionality. Added No attendance Alert

- frontend/platoon-console/src/components/CreateTeams.jsx
- frontend/platoon-console/src/pages/Homepage.jsx
- frontend/platoon-console/src/router.jsx
Created component to allow instructors to create teams
> 147 team generation component front end

- backend/API-DOCUMENTATION.md
- backend/platoon_console_proj/gh_api/views.py
- backend/platoon_console_proj/platoon_console_proj/settings.py
- frontend/platoon-console/src/components/Demo.jsx
- frontend/platoon-console/src/components/Github.jsx
- frontend/platoon-console/src/custom.scss
- frontend/platoon-console/src/pages/Homepage.jsx
* GitHub links show up in a scrollable card on HomePage.
- Closes #151
> 151 GitHub frontend links display

- frontend/platoon-console/package-lock.json
- frontend/platoon-console/package.json
- frontend/platoon-console/src/pages/CanvasPage.css
- frontend/platoon-console/src/pages/CanvasPage.jsx
- frontend/platoon-console/src/pages/Homepage.jsx
- frontend/platoon-console/src/router.jsx
Ability to use canvas, draw lines and rectangles and save screenshot as png to computer
- Closes #123 
(In this section, describe how to QA/review your PR. Feel free to use screenshots and/or short videos)
> 153 canvas

- frontend/platoon-console/src/components/Github.jsx
Changed <card> to <Card>
- Closes #151
> Fixed card > Card
